// source: model.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.Process', null, global);
goog.exportSymbol('proto.ProcessError', null, global);
goog.exportSymbol('proto.ProcessInput', null, global);
goog.exportSymbol('proto.Worker', null, global);
goog.exportSymbol('proto.WorkerIn', null, global);
goog.exportSymbol('proto.WorkerIn.DataCase', null, global);
goog.exportSymbol('proto.WorkerOut', null, global);
goog.exportSymbol('proto.WorkerOut.DataCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Worker = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Worker, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Worker.displayName = 'proto.Worker';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProcessInput = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ProcessInput, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ProcessInput.displayName = 'proto.ProcessInput';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProcessError = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ProcessError, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ProcessError.displayName = 'proto.ProcessError';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Process = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Process.repeatedFields_, null);
};
goog.inherits(proto.Process, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Process.displayName = 'proto.Process';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.WorkerIn = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.WorkerIn.oneofGroups_);
};
goog.inherits(proto.WorkerIn, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.WorkerIn.displayName = 'proto.WorkerIn';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.WorkerOut = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.WorkerOut.oneofGroups_);
};
goog.inherits(proto.WorkerOut, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.WorkerOut.displayName = 'proto.WorkerOut';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Worker.prototype.toObject = function(opt_includeInstance) {
  return proto.Worker.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Worker} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Worker.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, ""),
    version: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Worker}
 */
proto.Worker.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Worker;
  return proto.Worker.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Worker} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Worker}
 */
proto.Worker.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Worker.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Worker.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Worker} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Worker.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string type = 1;
 * @return {string}
 */
proto.Worker.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Worker} returns this
 */
proto.Worker.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string version = 2;
 * @return {string}
 */
proto.Worker.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Worker} returns this
 */
proto.Worker.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProcessInput.prototype.toObject = function(opt_includeInstance) {
  return proto.ProcessInput.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProcessInput} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ProcessInput.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, ""),
    version: jspb.Message.getFieldWithDefault(msg, 2, ""),
    caller: jspb.Message.getFieldWithDefault(msg, 3, ""),
    input: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ProcessInput}
 */
proto.ProcessInput.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ProcessInput;
  return proto.ProcessInput.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ProcessInput} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ProcessInput}
 */
proto.ProcessInput.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCaller(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setInput(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ProcessInput.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ProcessInput.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ProcessInput} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ProcessInput.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCaller();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getInput();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string type = 1;
 * @return {string}
 */
proto.ProcessInput.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ProcessInput} returns this
 */
proto.ProcessInput.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string version = 2;
 * @return {string}
 */
proto.ProcessInput.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ProcessInput} returns this
 */
proto.ProcessInput.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string caller = 3;
 * @return {string}
 */
proto.ProcessInput.prototype.getCaller = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ProcessInput} returns this
 */
proto.ProcessInput.prototype.setCaller = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string input = 4;
 * @return {string}
 */
proto.ProcessInput.prototype.getInput = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.ProcessInput} returns this
 */
proto.ProcessInput.prototype.setInput = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProcessError.prototype.toObject = function(opt_includeInstance) {
  return proto.ProcessError.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProcessError} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ProcessError.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    message: jspb.Message.getFieldWithDefault(msg, 2, ""),
    stack: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ProcessError}
 */
proto.ProcessError.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ProcessError;
  return proto.ProcessError.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ProcessError} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ProcessError}
 */
proto.ProcessError.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setStack(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ProcessError.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ProcessError.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ProcessError} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ProcessError.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStack();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.ProcessError.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ProcessError} returns this
 */
proto.ProcessError.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.ProcessError.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ProcessError} returns this
 */
proto.ProcessError.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string stack = 3;
 * @return {string}
 */
proto.ProcessError.prototype.getStack = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ProcessError} returns this
 */
proto.ProcessError.prototype.setStack = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Process.repeatedFields_ = [17];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Process.prototype.toObject = function(opt_includeInstance) {
  return proto.Process.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Process} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Process.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    created: jspb.Message.getFieldWithDefault(msg, 2, 0),
    type: jspb.Message.getFieldWithDefault(msg, 3, ""),
    version: jspb.Message.getFieldWithDefault(msg, 4, ""),
    status: jspb.Message.getFieldWithDefault(msg, 5, ""),
    currentTask: jspb.Message.getFieldWithDefault(msg, 6, ""),
    currentSubtask: jspb.Message.getFieldWithDefault(msg, 7, ""),
    currentInput: jspb.Message.getFieldWithDefault(msg, 8, ""),
    nextDeployTime: jspb.Message.getFieldWithDefault(msg, 9, 0),
    nextTask: jspb.Message.getFieldWithDefault(msg, 10, ""),
    nextSubtask: jspb.Message.getFieldWithDefault(msg, 11, ""),
    taskState: jspb.Message.getFieldWithDefault(msg, 12, ""),
    state: jspb.Message.getFieldWithDefault(msg, 13, ""),
    input: jspb.Message.getFieldWithDefault(msg, 14, ""),
    output: jspb.Message.getFieldWithDefault(msg, 15, ""),
    error: (f = msg.getError()) && proto.ProcessError.toObject(includeInstance, f),
    tagsList: (f = jspb.Message.getRepeatedField(msg, 17)) == null ? undefined : f,
    active: jspb.Message.getBooleanFieldWithDefault(msg, 18, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Process}
 */
proto.Process.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Process;
  return proto.Process.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Process} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Process}
 */
proto.Process.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCreated(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrentTask(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrentSubtask(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrentInput(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setNextDeployTime(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setNextTask(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setNextSubtask(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setTaskState(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setState(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setInput(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setOutput(value);
      break;
    case 16:
      var value = new proto.ProcessError;
      reader.readMessage(value,proto.ProcessError.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.addTags(value);
      break;
    case 18:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setActive(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Process.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Process.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Process} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Process.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCreated();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCurrentTask();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCurrentSubtask();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getCurrentInput();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getNextDeployTime();
  if (f !== 0) {
    writer.writeUint64(
      9,
      f
    );
  }
  f = message.getNextTask();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getNextSubtask();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getTaskState();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getState();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getInput();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getOutput();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      proto.ProcessError.serializeBinaryToWriter
    );
  }
  f = message.getTagsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      17,
      f
    );
  }
  f = message.getActive();
  if (f) {
    writer.writeBool(
      18,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.Process.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint64 created = 2;
 * @return {number}
 */
proto.Process.prototype.getCreated = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.setCreated = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string type = 3;
 * @return {string}
 */
proto.Process.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string version = 4;
 * @return {string}
 */
proto.Process.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string status = 5;
 * @return {string}
 */
proto.Process.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string current_task = 6;
 * @return {string}
 */
proto.Process.prototype.getCurrentTask = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.setCurrentTask = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string current_subtask = 7;
 * @return {string}
 */
proto.Process.prototype.getCurrentSubtask = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.setCurrentSubtask = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string current_input = 8;
 * @return {string}
 */
proto.Process.prototype.getCurrentInput = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.setCurrentInput = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional uint64 next_deploy_time = 9;
 * @return {number}
 */
proto.Process.prototype.getNextDeployTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.setNextDeployTime = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional string next_task = 10;
 * @return {string}
 */
proto.Process.prototype.getNextTask = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.setNextTask = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string next_subtask = 11;
 * @return {string}
 */
proto.Process.prototype.getNextSubtask = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.setNextSubtask = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string task_state = 12;
 * @return {string}
 */
proto.Process.prototype.getTaskState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.setTaskState = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string state = 13;
 * @return {string}
 */
proto.Process.prototype.getState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.setState = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string input = 14;
 * @return {string}
 */
proto.Process.prototype.getInput = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.setInput = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional string output = 15;
 * @return {string}
 */
proto.Process.prototype.getOutput = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.setOutput = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional ProcessError error = 16;
 * @return {?proto.ProcessError}
 */
proto.Process.prototype.getError = function() {
  return /** @type{?proto.ProcessError} */ (
    jspb.Message.getWrapperField(this, proto.ProcessError, 16));
};


/**
 * @param {?proto.ProcessError|undefined} value
 * @return {!proto.Process} returns this
*/
proto.Process.prototype.setError = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Process.prototype.hasError = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * repeated string tags = 17;
 * @return {!Array<string>}
 */
proto.Process.prototype.getTagsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 17));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.setTagsList = function(value) {
  return jspb.Message.setField(this, 17, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.addTags = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 17, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.clearTagsList = function() {
  return this.setTagsList([]);
};


/**
 * optional bool active = 18;
 * @return {boolean}
 */
proto.Process.prototype.getActive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 18, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Process} returns this
 */
proto.Process.prototype.setActive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 18, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.WorkerIn.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.WorkerIn.DataCase = {
  DATA_NOT_SET: 0,
  REGISTER_WORKER: 1,
  CREATE_PROCESS: 2,
  STEP_RESULT: 3
};

/**
 * @return {proto.WorkerIn.DataCase}
 */
proto.WorkerIn.prototype.getDataCase = function() {
  return /** @type {proto.WorkerIn.DataCase} */(jspb.Message.computeOneofCase(this, proto.WorkerIn.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.WorkerIn.prototype.toObject = function(opt_includeInstance) {
  return proto.WorkerIn.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.WorkerIn} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WorkerIn.toObject = function(includeInstance, msg) {
  var f, obj = {
    registerWorker: (f = msg.getRegisterWorker()) && proto.Worker.toObject(includeInstance, f),
    createProcess: (f = msg.getCreateProcess()) && proto.Process.toObject(includeInstance, f),
    stepResult: (f = msg.getStepResult()) && proto.Process.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.WorkerIn}
 */
proto.WorkerIn.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.WorkerIn;
  return proto.WorkerIn.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.WorkerIn} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.WorkerIn}
 */
proto.WorkerIn.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.Worker;
      reader.readMessage(value,proto.Worker.deserializeBinaryFromReader);
      msg.setRegisterWorker(value);
      break;
    case 2:
      var value = new proto.Process;
      reader.readMessage(value,proto.Process.deserializeBinaryFromReader);
      msg.setCreateProcess(value);
      break;
    case 3:
      var value = new proto.Process;
      reader.readMessage(value,proto.Process.deserializeBinaryFromReader);
      msg.setStepResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.WorkerIn.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.WorkerIn.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.WorkerIn} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WorkerIn.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRegisterWorker();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.Worker.serializeBinaryToWriter
    );
  }
  f = message.getCreateProcess();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.Process.serializeBinaryToWriter
    );
  }
  f = message.getStepResult();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.Process.serializeBinaryToWriter
    );
  }
};


/**
 * optional Worker register_worker = 1;
 * @return {?proto.Worker}
 */
proto.WorkerIn.prototype.getRegisterWorker = function() {
  return /** @type{?proto.Worker} */ (
    jspb.Message.getWrapperField(this, proto.Worker, 1));
};


/**
 * @param {?proto.Worker|undefined} value
 * @return {!proto.WorkerIn} returns this
*/
proto.WorkerIn.prototype.setRegisterWorker = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.WorkerIn.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WorkerIn} returns this
 */
proto.WorkerIn.prototype.clearRegisterWorker = function() {
  return this.setRegisterWorker(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WorkerIn.prototype.hasRegisterWorker = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Process create_process = 2;
 * @return {?proto.Process}
 */
proto.WorkerIn.prototype.getCreateProcess = function() {
  return /** @type{?proto.Process} */ (
    jspb.Message.getWrapperField(this, proto.Process, 2));
};


/**
 * @param {?proto.Process|undefined} value
 * @return {!proto.WorkerIn} returns this
*/
proto.WorkerIn.prototype.setCreateProcess = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.WorkerIn.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WorkerIn} returns this
 */
proto.WorkerIn.prototype.clearCreateProcess = function() {
  return this.setCreateProcess(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WorkerIn.prototype.hasCreateProcess = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Process step_result = 3;
 * @return {?proto.Process}
 */
proto.WorkerIn.prototype.getStepResult = function() {
  return /** @type{?proto.Process} */ (
    jspb.Message.getWrapperField(this, proto.Process, 3));
};


/**
 * @param {?proto.Process|undefined} value
 * @return {!proto.WorkerIn} returns this
*/
proto.WorkerIn.prototype.setStepResult = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.WorkerIn.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WorkerIn} returns this
 */
proto.WorkerIn.prototype.clearStepResult = function() {
  return this.setStepResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WorkerIn.prototype.hasStepResult = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.WorkerOut.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.WorkerOut.DataCase = {
  DATA_NOT_SET: 0,
  VALIDATE_INPUT: 1,
  MAKE_STEP: 2
};

/**
 * @return {proto.WorkerOut.DataCase}
 */
proto.WorkerOut.prototype.getDataCase = function() {
  return /** @type {proto.WorkerOut.DataCase} */(jspb.Message.computeOneofCase(this, proto.WorkerOut.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.WorkerOut.prototype.toObject = function(opt_includeInstance) {
  return proto.WorkerOut.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.WorkerOut} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WorkerOut.toObject = function(includeInstance, msg) {
  var f, obj = {
    validateInput: (f = msg.getValidateInput()) && proto.ProcessInput.toObject(includeInstance, f),
    makeStep: (f = msg.getMakeStep()) && proto.Process.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.WorkerOut}
 */
proto.WorkerOut.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.WorkerOut;
  return proto.WorkerOut.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.WorkerOut} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.WorkerOut}
 */
proto.WorkerOut.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ProcessInput;
      reader.readMessage(value,proto.ProcessInput.deserializeBinaryFromReader);
      msg.setValidateInput(value);
      break;
    case 2:
      var value = new proto.Process;
      reader.readMessage(value,proto.Process.deserializeBinaryFromReader);
      msg.setMakeStep(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.WorkerOut.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.WorkerOut.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.WorkerOut} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WorkerOut.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValidateInput();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.ProcessInput.serializeBinaryToWriter
    );
  }
  f = message.getMakeStep();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.Process.serializeBinaryToWriter
    );
  }
};


/**
 * optional ProcessInput validate_input = 1;
 * @return {?proto.ProcessInput}
 */
proto.WorkerOut.prototype.getValidateInput = function() {
  return /** @type{?proto.ProcessInput} */ (
    jspb.Message.getWrapperField(this, proto.ProcessInput, 1));
};


/**
 * @param {?proto.ProcessInput|undefined} value
 * @return {!proto.WorkerOut} returns this
*/
proto.WorkerOut.prototype.setValidateInput = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.WorkerOut.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WorkerOut} returns this
 */
proto.WorkerOut.prototype.clearValidateInput = function() {
  return this.setValidateInput(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WorkerOut.prototype.hasValidateInput = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Process make_step = 2;
 * @return {?proto.Process}
 */
proto.WorkerOut.prototype.getMakeStep = function() {
  return /** @type{?proto.Process} */ (
    jspb.Message.getWrapperField(this, proto.Process, 2));
};


/**
 * @param {?proto.Process|undefined} value
 * @return {!proto.WorkerOut} returns this
*/
proto.WorkerOut.prototype.setMakeStep = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.WorkerOut.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WorkerOut} returns this
 */
proto.WorkerOut.prototype.clearMakeStep = function() {
  return this.setMakeStep(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WorkerOut.prototype.hasMakeStep = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto);
